spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:

  application:
    name: bot
  config:
    import: "classpath:common.yaml"
---
spring:
  config:
    import: "classpath:common-dev.yaml"
    activate:
      on-profile: dev
---
spring:
  config:
    import: "classpath:common-prod.yaml"
    activate:
      on-profile: prod
